
services:
    mongodb:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
            - MONGO_INITDB_DATABASE=${DB_NAME:-todos_database}
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
        depends_on:
            - mongodb  
    books:
        build: .
        ports:
            - 80:3000
        environment:
            - PORT=3000
            - DB_USERNAME=${DB_USERNAME:-root}
            - DB_PASSWORD=${DB_PASSWORD:-password}
            - DB_NAME=${DB_NAME:-todos_database}
            - DB_HOST=mongodb://localhost:27017/todos_database
        depends_on:
            - mongodb