services:
    redis:
        image: "redis"
    counter:
        build: .
        ports:
            - 80:3000
        environment:
            - PORT=3000
            - REDIS_URL=redis
        links: 
            - redis
