services:
    redis:
        image: redis
    counter:
        build: .
        ports:
            - 80:3000
        environment:
            - PORT=3000
            - REDIS_URL=redis
        links: 
            - redis
    mongo:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_DATABASE=db
    mongo-express:
        image: mongo-express
        restart: always
        ports: 
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example


            